<a href="https://colab.research.google.com/github/shcho11/04.IBM_AIEngineering_Pytorch/blob/main/Pytorch_MultipleLinearRegression_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Multiple Linear Regression</h1>


<h2>Objective</h2><ul><li> How to make the prediction for multiple inputs.</li><li> How to use linear class to build more complex models.</li><li> How to build a custom module.</li></ul> 


<h2>Preparation</h2>


Import the libraries and set the random seed.


In [1]:
# Import the libraries and set the random seed

from torch import nn
import torch
torch.manual_seed(1)

<h2 id="Prediction">Prediction</h2>


Set weight and bias.


In [2]:
# Set the weight and bias

w = torch.tensor([[2.0], [3.0]], requires_grad=True)
b = torch.tensor([[1.0]], requires_grad=True)

# requires_grad 의 의미 : "이 변수는 학습을 통해 계속 값이 변경되는 변수" 
#                         (마찬가지로 편향 도 0으로 초기화하고, 학습을 통해 값이 변경되는 변수임을 명시)

In [3]:
print(w)
print(w.shape, "\n")
print(b)
print(b.shape)

tensor([[2.],
        [3.]], requires_grad=True)
torch.Size([2, 1]) 

tensor([[1.]], requires_grad=True)
torch.Size([1, 1])


Define the parameters. <code>torch.mm</code> uses matrix multiplication instead of scaler multiplication.


In [4]:
# Define Prediction Function
# mm은 input과 mat2에 대해서 matrix multiplication을 수행하는 함수. 이 함수는 broadcast되지 않는 것이 특징.
# 즉 mm은 정확하게 matrix 곱의 사이즈가 맞아야 사용이 가능. 만약 broadcasting된 것을 원한다면 torch.matul 함수를 사용해야 함.

def forward(x):
    yhat = torch.mm(x, w) + b
    return yhat

If we input a <i>1x2</i> tensor, because we have a <i>2x1</i> tensor as <code>w</code>, we will get a <i>1x1</i> tensor:


In [5]:
# Calculate yhat

x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print("The result: ", yhat)

The result:  tensor([[9.]], grad_fn=<AddBackward0>)


## Each row of the following tensor represents a sample:


In [6]:
# Sample tensor X

X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])

In [7]:
# Make the prediction of X 

yhat = forward(X)
print("The result: ", yhat)

The result:  tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


<h2 id="Linear">Class Linear</h2>


We can use the linear class to make a prediction. You'll also use the linear class to build more complex models.


In [8]:
# Make a linear regression model using build-in function

model = nn.Linear(2, 1)
print(model)

Linear(in_features=2, out_features=1, bias=True)


In [10]:
print(model.parameters())
print(model.state_dict())

<generator object Module.parameters at 0x7f66fa6d2dd0>
OrderedDict([('weight', tensor([[ 0.3643, -0.3121]])), ('bias', tensor([-0.1371]))])


Make a prediction with the first sample:


In [11]:
# Make a prediction of x

yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[-0.3969]], grad_fn=<AddmmBackward0>)


Predict with multiple samples <code>X</code>:


In [12]:
# Make a prediction of X

yhat = model(X)
print("The result: ", yhat)

The result:  tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward0>)


<h2 id="Cust">Build Custom Modules </h2>


Now, you'll build a custom module. You can make more complex models by using this method later.


In [13]:
# Create linear_regression Class

class linear_regression(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

Build a linear regression object. The input feature size is two.


In [14]:
model = linear_regression(2, 1)

You can see the randomly initialized parameters by using the <code>parameters()</code> method:


In [15]:
# Print model parameters

print("The parameters: ", list(model.parameters()))

The parameters:  [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


You can also see the parameters by using the <code>state_dict()</code> method:


In [16]:
# Print model parameters

print("The parameters: ", model.state_dict())

The parameters:  OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])), ('linear.bias', tensor([0.4241]))])


Now we input a 1x2 tensor, and we will get a 1x1 tensor.


In [17]:
# Make a prediction of x

yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[-0.5754]], grad_fn=<AddmmBackward0>)


Make a prediction for multiple samples:


In [18]:
# Make a prediction of X

yhat = model(X)
print("The result: ", yhat)

The result:  tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward0>)


The shape is shown in the following image:


<h3>Practice</h3>


Build a model or object of type <code>linear_regression</code>. Using the <code>linear_regression</code> object will predict the following tensor:


In [19]:
# Practice: Build a model to predict the follow tensor.

X = torch.tensor([[11.0, 12.0, 13, 14], [11, 12, 13, 14]])

model = linear_regression(4, 1)
yhat = model(X)

print("The result: ", yhat)

The result:  tensor([[2.1062],
        [2.1062]], grad_fn=<AddmmBackward0>)
